<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: any.proto

namespace GPBMetadata;

class Any
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd010a09616e792e70726f746f120f70726f746f6275662e4761727564" .
            "6122260a03416e7912100a08747970655f75726c180120012809120d0a05" .
            "76616c756518022001280c426f0a13636f6d2e676f6f676c652e70726f74" .
            "6f6275664208416e7950726f746f50015a256769746875622e636f6d2f67" .
            "6f6c616e672f70726f746f6275662f7074797065732f616e79a202034750" .
            "42aa021e476f6f676c652e50726f746f6275662e57656c6c4b6e6f776e54" .
            "79706573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

