<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMPresenceAuth.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *明文秘钥CK结构
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.Ck</code>
 */
class Ck extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 uId = 1;</code>
     */
    private $uId = 0;
    /**
     * <code>int64 timestamp = 2;</code>
     */
    private $timestamp = 0;

    public function __construct() {
        \GPBMetadata\IMPresenceAuth::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 uId = 1;</code>
     */
    public function getUId()
    {
        return $this->uId;
    }

    /**
     * <code>int64 uId = 1;</code>
     */
    public function setUId($var)
    {
        GPBUtil::checkInt64($var);
        $this->uId = $var;
    }

    /**
     * <code>int64 timestamp = 2;</code>
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * <code>int64 timestamp = 2;</code>
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;
    }

}

