<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMConstant.proto

namespace Protobuf\Garuda;

/**
 * <pre>
 * 消息的跳转类型
 * </pre>
 *
 * Protobuf enum <code>protobuf.Garuda.GotoType</code>
 */
class GotoType
{
    /**
     * <pre>
     *默认，客户端根据消息类型自行选择
     * </pre>
     *
     * <code>CUSTOM = 0;</code>
     */
    const CUSTOM = 0;
    /**
     * <pre>
     *跳转到直播间
     * </pre>
     *
     * <code>LIVEROM = 1;</code>
     */
    const LIVEROM = 1;
    /**
     * <pre>
     *跳转到个人profile页面
     * </pre>
     *
     * <code>PROFILE = 2;</code>
     */
    const PROFILE = 2;
    /**
     * <pre>
     *跳转到内部浏览器
     * </pre>
     *
     * <code>INNER_H5 = 3;</code>
     */
    const INNER_H5 = 3;
    /**
     * <pre>
     *跳转到外部浏览器
     * </pre>
     *
     * <code>OUTER_H5 = 4;</code>
     */
    const OUTER_H5 = 4;
    /**
     * <pre>
     *跳转至“我的等级”
     * </pre>
     *
     * <code>MY_GRADE = 5;</code>
     */
    const MY_GRADE = 5;
    /**
     * <pre>
     *跳转至“我的会员”
     * </pre>
     *
     * <code>MY_VIP = 6;</code>
     */
    const MY_VIP = 6;
    /**
     * <pre>
     *跳转至“我的背包”
     * </pre>
     *
     * <code>MY_PACK = 7;</code>
     */
    const MY_PACK = 7;
    /**
     * <pre>
     *跳转至“我的背包—过期礼物”
     * </pre>
     *
     * <code>MY_PACK_EXPIRE_GIFT = 8;</code>
     */
    const MY_PACK_EXPIRE_GIFT = 8;
    /**
     * <pre>
     *跳转到动态详情
     * </pre>
     *
     * <code>DYNAMIC_DETAIL = 9;</code>
     */
    const DYNAMIC_DETAIL = 9;
    /**
     * <pre>
     *跳转到vip客服
     * </pre>
     *
     * <code>VIP_CS = 10;</code>
     */
    const VIP_CS = 10;
    /**
     * <pre>
     *跳转入群
     * </pre>
     *
     * <code>GROUP_JOIN = 11;</code>
     */
    const GROUP_JOIN = 11;
}

