<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgActivity.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *拉取群消息离线上行，支持多个群离线
 *适用于：
 *消息类型 type = PULL_ACT（拉取动作）
 *业务类型 mType = PULL_GROUP_MSG（拉取群的消息）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.GroupOfflineReq</code>
 */
class GroupOfflineReq extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protobuf.Garuda.OfflineReq OfflineReq = 1;</code>
     */
    private $OfflineReq;

    public function __construct() {
        \GPBMetadata\IMMsgActivity::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protobuf.Garuda.OfflineReq OfflineReq = 1;</code>
     */
    public function getOfflineReq()
    {
        return $this->OfflineReq;
    }

    /**
     * <code>repeated .protobuf.Garuda.OfflineReq OfflineReq = 1;</code>
     */
    public function setOfflineReq(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protobuf\Garuda\OfflineReq::class);
        $this->OfflineReq = $arr;
    }

}

