<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMServerActivity.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *IM内部注册报文
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.InternalRegister</code>
 */
class InternalRegister extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *服务器类型
     * </pre>
     *
     * <code>int32 sType = 1;</code>
     */
    private $sType = 0;
    /**
     * <pre>
     *ip
     * </pre>
     *
     * <code>string ip = 2;</code>
     */
    private $ip = '';
    /**
     * <pre>
     *端口号
     * </pre>
     *
     * <code>int32 port = 3;</code>
     */
    private $port = 0;

    public function __construct() {
        \GPBMetadata\IMServerActivity::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *服务器类型
     * </pre>
     *
     * <code>int32 sType = 1;</code>
     */
    public function getSType()
    {
        return $this->sType;
    }

    /**
     * <pre>
     *服务器类型
     * </pre>
     *
     * <code>int32 sType = 1;</code>
     */
    public function setSType($var)
    {
        GPBUtil::checkInt32($var);
        $this->sType = $var;
    }

    /**
     * <pre>
     *ip
     * </pre>
     *
     * <code>string ip = 2;</code>
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * <pre>
     *ip
     * </pre>
     *
     * <code>string ip = 2;</code>
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;
    }

    /**
     * <pre>
     *端口号
     * </pre>
     *
     * <code>int32 port = 3;</code>
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * <pre>
     *端口号
     * </pre>
     *
     * <code>int32 port = 3;</code>
     */
    public function setPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->port = $var;
    }

}

