<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgContent.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *气泡
 *消息格式： mformat = BUBBLE（气泡）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.MsgBubble</code>
 */
class MsgBubble extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    private $content = '';
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    private $title = '';
    /**
     * <pre>
     * 图片url
     * </pre>
     *
     * <code>string picUrl = 3;</code>
     */
    private $picUrl = '';
    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 4;</code>
     */
    private $gotoType = 0;
    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 5;</code>
     */
    private $bizBody = '';

    public function __construct() {
        \GPBMetadata\IMMsgContent::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;
    }

    /**
     * <pre>
     * 图片url
     * </pre>
     *
     * <code>string picUrl = 3;</code>
     */
    public function getPicUrl()
    {
        return $this->picUrl;
    }

    /**
     * <pre>
     * 图片url
     * </pre>
     *
     * <code>string picUrl = 3;</code>
     */
    public function setPicUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->picUrl = $var;
    }

    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 4;</code>
     */
    public function getGotoType()
    {
        return $this->gotoType;
    }

    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 4;</code>
     */
    public function setGotoType($var)
    {
        GPBUtil::checkInt32($var);
        $this->gotoType = $var;
    }

    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 5;</code>
     */
    public function getBizBody()
    {
        return $this->bizBody;
    }

    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 5;</code>
     */
    public function setBizBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->bizBody = $var;
    }

}

