<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMConstant.proto

namespace Protobuf\Garuda;

/**
 * <pre>
 * 消息的格式，决定消息的格式内容
 * </pre>
 *
 * Protobuf enum <code>protobuf.Garuda.MsgFormat</code>
 */
class MsgFormat
{
    /**
     * <pre>
     *默认，普通纯文本消息
     * </pre>
     *
     * <code>TEXT = 0;</code>
     */
    const TEXT = 0;
    /**
     * <pre>
     *附带跳转动作的文本消息
     * </pre>
     *
     * <code>GOTO_TEXT = 1;</code>
     */
    const GOTO_TEXT = 1;
    /**
     * <pre>
     *普通纯图片消息
     * </pre>
     *
     * <code>PIC = 2;</code>
     */
    const PIC = 2;
    /**
     * <pre>
     *附带跳转动作的图片消息
     * </pre>
     *
     * <code>GOTO_PIC = 3;</code>
     */
    const GOTO_PIC = 3;
    /**
     * <pre>
     *音频
     * </pre>
     *
     * <code>AUDIO = 4;</code>
     */
    const AUDIO = 4;
    /**
     * <pre>
     *视频
     * </pre>
     *
     * <code>VIDEO = 5;</code>
     */
    const VIDEO = 5;
    /**
     * <pre>
     *分享链接
     * </pre>
     *
     * <code>LINK = 6;</code>
     */
    const LINK = 6;
    /**
     * <pre>
     *气泡
     * </pre>
     *
     * <code>BUBBLE = 7;</code>
     */
    const BUBBLE = 7;
    /**
     * <pre>
     *礼物
     * </pre>
     *
     * <code>GIFT = 8;</code>
     */
    const GIFT = 8;
}

