<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgContent.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *跳转类图片消息
 *消息格式： mformat = GOTO_PIC（图片）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.MsgGotoPic</code>
 */
class MsgGotoPic extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    private $content = '';
    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 2;</code>
     */
    private $gotoType = 0;
    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *name : '链接名称' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 3;</code>
     */
    private $bizBody = '';
    /**
     * <pre>
     *图片名称
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    private $name = '';
    /**
     * <pre>
     *图片url
     * </pre>
     *
     * <code>string url = 5;</code>
     */
    private $url = '';
    /**
     * <pre>
     *小图片二进制流
     * </pre>
     *
     * <code>bytes pic = 6;</code>
     */
    private $pic = '';
    /**
     * <pre>
     *图片后缀
     * </pre>
     *
     * <code>string ext = 7;</code>
     */
    private $ext = '';
    /**
     * <pre>
     *宽
     * </pre>
     *
     * <code>double w = 8;</code>
     */
    private $w = 0.0;
    /**
     * <pre>
     *高
     * </pre>
     *
     * <code>double h = 9;</code>
     */
    private $h = 0.0;
    /**
     * <pre>
     *大小
     * </pre>
     *
     * <code>double size = 10;</code>
     */
    private $size = 0.0;

    public function __construct() {
        \GPBMetadata\IMMsgContent::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 2;</code>
     */
    public function getGotoType()
    {
        return $this->gotoType;
    }

    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 2;</code>
     */
    public function setGotoType($var)
    {
        GPBUtil::checkInt32($var);
        $this->gotoType = $var;
    }

    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *name : '链接名称' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 3;</code>
     */
    public function getBizBody()
    {
        return $this->bizBody;
    }

    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *name : '链接名称' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 3;</code>
     */
    public function setBizBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->bizBody = $var;
    }

    /**
     * <pre>
     *图片名称
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     *图片名称
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     *图片url
     * </pre>
     *
     * <code>string url = 5;</code>
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * <pre>
     *图片url
     * </pre>
     *
     * <code>string url = 5;</code>
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;
    }

    /**
     * <pre>
     *小图片二进制流
     * </pre>
     *
     * <code>bytes pic = 6;</code>
     */
    public function getPic()
    {
        return $this->pic;
    }

    /**
     * <pre>
     *小图片二进制流
     * </pre>
     *
     * <code>bytes pic = 6;</code>
     */
    public function setPic($var)
    {
        GPBUtil::checkString($var, False);
        $this->pic = $var;
    }

    /**
     * <pre>
     *图片后缀
     * </pre>
     *
     * <code>string ext = 7;</code>
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * <pre>
     *图片后缀
     * </pre>
     *
     * <code>string ext = 7;</code>
     */
    public function setExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->ext = $var;
    }

    /**
     * <pre>
     *宽
     * </pre>
     *
     * <code>double w = 8;</code>
     */
    public function getW()
    {
        return $this->w;
    }

    /**
     * <pre>
     *宽
     * </pre>
     *
     * <code>double w = 8;</code>
     */
    public function setW($var)
    {
        GPBUtil::checkDouble($var);
        $this->w = $var;
    }

    /**
     * <pre>
     *高
     * </pre>
     *
     * <code>double h = 9;</code>
     */
    public function getH()
    {
        return $this->h;
    }

    /**
     * <pre>
     *高
     * </pre>
     *
     * <code>double h = 9;</code>
     */
    public function setH($var)
    {
        GPBUtil::checkDouble($var);
        $this->h = $var;
    }

    /**
     * <pre>
     *大小
     * </pre>
     *
     * <code>double size = 10;</code>
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * <pre>
     *大小
     * </pre>
     *
     * <code>double size = 10;</code>
     */
    public function setSize($var)
    {
        GPBUtil::checkDouble($var);
        $this->size = $var;
    }

}

