<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgContent.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *礼物
 *消息格式： mformat = GIFT（礼物）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.MsgGift</code>
 */
class MsgGift extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    private $content = '';
    /**
     * <pre>
     *礼物ID
     * </pre>
     *
     * <code>int64 giftId = 2;</code>
     */
    private $giftId = 0;
    /**
     * <pre>
     *礼物名称
     * </pre>
     *
     * <code>string giftName = 3;</code>
     */
    private $giftName = '';
    /**
     * <pre>
     *礼物数量
     * </pre>
     *
     * <code>int32 giftAmount = 4;</code>
     */
    private $giftAmount = 0;
    /**
     * <pre>
     *是否连续
     * </pre>
     *
     * <code>bool isContinuous = 5;</code>
     */
    private $isContinuous = false;
    /**
     * <pre>
     *连续次数
     * </pre>
     *
     * <code>int32 numContinuous = 6;</code>
     */
    private $numContinuous = 0;
    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 7;</code>
     */
    private $gotoType = 0;
    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 8;</code>
     */
    private $bizBody = '';

    public function __construct() {
        \GPBMetadata\IMMsgContent::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

    /**
     * <pre>
     *礼物ID
     * </pre>
     *
     * <code>int64 giftId = 2;</code>
     */
    public function getGiftId()
    {
        return $this->giftId;
    }

    /**
     * <pre>
     *礼物ID
     * </pre>
     *
     * <code>int64 giftId = 2;</code>
     */
    public function setGiftId($var)
    {
        GPBUtil::checkInt64($var);
        $this->giftId = $var;
    }

    /**
     * <pre>
     *礼物名称
     * </pre>
     *
     * <code>string giftName = 3;</code>
     */
    public function getGiftName()
    {
        return $this->giftName;
    }

    /**
     * <pre>
     *礼物名称
     * </pre>
     *
     * <code>string giftName = 3;</code>
     */
    public function setGiftName($var)
    {
        GPBUtil::checkString($var, True);
        $this->giftName = $var;
    }

    /**
     * <pre>
     *礼物数量
     * </pre>
     *
     * <code>int32 giftAmount = 4;</code>
     */
    public function getGiftAmount()
    {
        return $this->giftAmount;
    }

    /**
     * <pre>
     *礼物数量
     * </pre>
     *
     * <code>int32 giftAmount = 4;</code>
     */
    public function setGiftAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->giftAmount = $var;
    }

    /**
     * <pre>
     *是否连续
     * </pre>
     *
     * <code>bool isContinuous = 5;</code>
     */
    public function getIsContinuous()
    {
        return $this->isContinuous;
    }

    /**
     * <pre>
     *是否连续
     * </pre>
     *
     * <code>bool isContinuous = 5;</code>
     */
    public function setIsContinuous($var)
    {
        GPBUtil::checkBool($var);
        $this->isContinuous = $var;
    }

    /**
     * <pre>
     *连续次数
     * </pre>
     *
     * <code>int32 numContinuous = 6;</code>
     */
    public function getNumContinuous()
    {
        return $this->numContinuous;
    }

    /**
     * <pre>
     *连续次数
     * </pre>
     *
     * <code>int32 numContinuous = 6;</code>
     */
    public function setNumContinuous($var)
    {
        GPBUtil::checkInt32($var);
        $this->numContinuous = $var;
    }

    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 7;</code>
     */
    public function getGotoType()
    {
        return $this->gotoType;
    }

    /**
     * <pre>
     * 消息的跳转类型,详见 GotoType 枚举，Constant.GotoType
     * </pre>
     *
     * <code>int32 gotoType = 7;</code>
     */
    public function setGotoType($var)
    {
        GPBUtil::checkInt32($var);
        $this->gotoType = $var;
    }

    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 8;</code>
     */
    public function getBizBody()
    {
        return $this->bizBody;
    }

    /**
     * <pre>
     **业务实体，json字符串，用于具体业务
     *结构   {
     *uid : '需要跳转到profile的用户id' ,
     *roomId  '跳转到直播间的 roomId' ,
     *url : '链接url' ,
     *... 根据业务可以进行扩展，供业务端和客户端使用。
     *}
     * </pre>
     *
     * <code>string bizBody = 8;</code>
     */
    public function setBizBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->bizBody = $var;
    }

}

