<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgContent.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *普通纯图片消息
 *消息格式： mformat = PIC（图片）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.MsgPic</code>
 */
class MsgPic extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    private $content = '';
    /**
     * <pre>
     *原图片url
     * </pre>
     *
     * <code>string origUrl = 2;</code>
     */
    private $origUrl = '';
    /**
     * <pre>
     *缩略图文件
     * </pre>
     *
     * <code>bytes thumbFile = 3;</code>
     */
    private $thumbFile = '';
    /**
     * <pre>
     *图片后缀
     * </pre>
     *
     * <code>string ext = 4;</code>
     */
    private $ext = '';
    /**
     * <pre>
     *原图宽
     * </pre>
     *
     * <code>int32 w = 5;</code>
     */
    private $w = 0;
    /**
     * <pre>
     *原图高
     * </pre>
     *
     * <code>int32 h = 6;</code>
     */
    private $h = 0;
    /**
     * <pre>
     *原图大小
     * </pre>
     *
     * <code>int64 size = 7;</code>
     */
    private $size = 0;
    /**
     * <pre>
     *中等缩略图片url
     * </pre>
     *
     * <code>string midUrl = 8;</code>
     */
    private $midUrl = '';

    public function __construct() {
        \GPBMetadata\IMMsgContent::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

    /**
     * <pre>
     *原图片url
     * </pre>
     *
     * <code>string origUrl = 2;</code>
     */
    public function getOrigUrl()
    {
        return $this->origUrl;
    }

    /**
     * <pre>
     *原图片url
     * </pre>
     *
     * <code>string origUrl = 2;</code>
     */
    public function setOrigUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->origUrl = $var;
    }

    /**
     * <pre>
     *缩略图文件
     * </pre>
     *
     * <code>bytes thumbFile = 3;</code>
     */
    public function getThumbFile()
    {
        return $this->thumbFile;
    }

    /**
     * <pre>
     *缩略图文件
     * </pre>
     *
     * <code>bytes thumbFile = 3;</code>
     */
    public function setThumbFile($var)
    {
        GPBUtil::checkString($var, False);
        $this->thumbFile = $var;
    }

    /**
     * <pre>
     *图片后缀
     * </pre>
     *
     * <code>string ext = 4;</code>
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * <pre>
     *图片后缀
     * </pre>
     *
     * <code>string ext = 4;</code>
     */
    public function setExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->ext = $var;
    }

    /**
     * <pre>
     *原图宽
     * </pre>
     *
     * <code>int32 w = 5;</code>
     */
    public function getW()
    {
        return $this->w;
    }

    /**
     * <pre>
     *原图宽
     * </pre>
     *
     * <code>int32 w = 5;</code>
     */
    public function setW($var)
    {
        GPBUtil::checkInt32($var);
        $this->w = $var;
    }

    /**
     * <pre>
     *原图高
     * </pre>
     *
     * <code>int32 h = 6;</code>
     */
    public function getH()
    {
        return $this->h;
    }

    /**
     * <pre>
     *原图高
     * </pre>
     *
     * <code>int32 h = 6;</code>
     */
    public function setH($var)
    {
        GPBUtil::checkInt32($var);
        $this->h = $var;
    }

    /**
     * <pre>
     *原图大小
     * </pre>
     *
     * <code>int64 size = 7;</code>
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * <pre>
     *原图大小
     * </pre>
     *
     * <code>int64 size = 7;</code>
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;
    }

    /**
     * <pre>
     *中等缩略图片url
     * </pre>
     *
     * <code>string midUrl = 8;</code>
     */
    public function getMidUrl()
    {
        return $this->midUrl;
    }

    /**
     * <pre>
     *中等缩略图片url
     * </pre>
     *
     * <code>string midUrl = 8;</code>
     */
    public function setMidUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->midUrl = $var;
    }

}

