<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgContent.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *普通纯文本消息
 *消息格式： mformat = TEXT（文本）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.MsgText</code>
 */
class MsgText extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    private $content = '';

    public function __construct() {
        \GPBMetadata\IMMsgContent::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

}

