<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgContent.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *多语言系统消息
 *适用于：
 *系统类消息（且是多语言 multilang ＝ 1）：Type = SYS_VN（系统通知）、SYS_VG（系统群通知）、SYS_BROADCAST（系统广播）
 *map&lt;string,bytes&gt; langContents 中的 value(body) 可用于该 Type 下的所有业务类型 MsgType 以及消息格式 MsgFormat。
 * </pre>
 *
 * Protobuf type <code>Protobuf.Garuda.MultilangSysMsg</code>
 */
class MultilangSysMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *默认语言
     * </pre>
     *
     * <code>string defLang = 1;</code>
     */
    private $defLang = '';
    /**
     * <pre>
     * key:lang value:body , multi 与 Message.body 内容规则相同
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; langContents = 2;</code>
     */
    private $langContents;

    public function __construct() {
        \GPBMetadata\MsgContent::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *默认语言
     * </pre>
     *
     * <code>string defLang = 1;</code>
     */
    public function getDefLang()
    {
        return $this->defLang;
    }

    /**
     * <pre>
     *默认语言
     * </pre>
     *
     * <code>string defLang = 1;</code>
     */
    public function setDefLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->defLang = $var;
    }

    /**
     * <pre>
     * key:lang value:body , multi 与 Message.body 内容规则相同
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; langContents = 2;</code>
     */
    public function getLangContents()
    {
        return $this->langContents;
    }

    /**
     * <pre>
     * key:lang value:body , multi 与 Message.body 内容规则相同
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; langContents = 2;</code>
     */
    public function setLangContents(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->langContents = $arr;
    }

}

