<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgActivity.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *拉取离线消息下行报文体
 *适用于：
 *消息类型 ：type = PULLACT（拉取动作）
 *业务类型 ：mType = PULLOFFLINEMSG（拉取离线消息）、PULLGROUPMSG（拉取群的消息）、PULLSYSMSG（拉取系统广播的消息）、PULLRECENTMSG（拉取最近的消息）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.OfflineRes</code>
 */
class OfflineRes extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protobuf.Garuda.GMessage offlineMsg = 1;</code>
     */
    private $offlineMsg;

    public function __construct() {
        \GPBMetadata\IMMsgActivity::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protobuf.Garuda.GMessage offlineMsg = 1;</code>
     */
    public function getOfflineMsg()
    {
        return $this->offlineMsg;
    }

    /**
     * <code>repeated .protobuf.Garuda.GMessage offlineMsg = 1;</code>
     */
    public function setOfflineMsg(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protobuf\Garuda\GMessage::class);
        $this->offlineMsg = $arr;
    }

}

