<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgActivity.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *拉取离线消息上行报文体
 *适用于：
 *消息类型 ：type = PULLACT（拉取动作）
 *业务类型 ：mType = PULLOFFLINEMSG（拉取离线消息）、PULLGROUPMSG（拉取群的消息）、PULLSYSMSG（拉取系统广播的消息）、PULLRECENTMSG（拉取最近的消息）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.OfflineReq</code>
 */
class OfflineReq extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *开始版本，Client 本地版本
     * </pre>
     *
     * <code>int64 startVersion = 1;</code>
     */
    private $startVersion = 0;
    /**
     * <pre>
     *结束版本
     * </pre>
     *
     * <code>int64 endVersion = 2;</code>
     */
    private $endVersion = 0;
    /**
     * <pre>
     *拉取的版本号
     * </pre>
     *
     * <code>repeated int64 msgVersions = 3;</code>
     */
    private $msgVersions;
    /**
     * <pre>
     * 语言
     * </pre>
     *
     * <code>string lang = 4;</code>
     */
    private $lang = '';
    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>int64 gId = 5;</code>
     */
    private $gId = 0;

    public function __construct() {
        \GPBMetadata\IMMsgActivity::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *开始版本，Client 本地版本
     * </pre>
     *
     * <code>int64 startVersion = 1;</code>
     */
    public function getStartVersion()
    {
        return $this->startVersion;
    }

    /**
     * <pre>
     *开始版本，Client 本地版本
     * </pre>
     *
     * <code>int64 startVersion = 1;</code>
     */
    public function setStartVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->startVersion = $var;
    }

    /**
     * <pre>
     *结束版本
     * </pre>
     *
     * <code>int64 endVersion = 2;</code>
     */
    public function getEndVersion()
    {
        return $this->endVersion;
    }

    /**
     * <pre>
     *结束版本
     * </pre>
     *
     * <code>int64 endVersion = 2;</code>
     */
    public function setEndVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->endVersion = $var;
    }

    /**
     * <pre>
     *拉取的版本号
     * </pre>
     *
     * <code>repeated int64 msgVersions = 3;</code>
     */
    public function getMsgVersions()
    {
        return $this->msgVersions;
    }

    /**
     * <pre>
     *拉取的版本号
     * </pre>
     *
     * <code>repeated int64 msgVersions = 3;</code>
     */
    public function setMsgVersions(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->msgVersions = $arr;
    }

    /**
     * <pre>
     * 语言
     * </pre>
     *
     * <code>string lang = 4;</code>
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * <pre>
     * 语言
     * </pre>
     *
     * <code>string lang = 4;</code>
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;
    }

    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>int64 gId = 5;</code>
     */
    public function getGId()
    {
        return $this->gId;
    }

    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>int64 gId = 5;</code>
     */
    public function setGId($var)
    {
        GPBUtil::checkInt64($var);
        $this->gId = $var;
    }

}

