<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgActivity.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *离线消息实体
 *适用于：
 *拉取离线消息下行
 * </pre>
 *
 * Protobuf type <code>Protobuf.Garuda.OfflineMsg</code>
 */
class OfflineMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *消息ID,用于记录消息唯一标识(例如server端回ACK时,客户端可根据此ID唯一标识),对于业务报文此参数为必须
     * </pre>
     *
     * <code>string msgid = 1;</code>
     */
    private $msgid = '';
    /**
     * <pre>
     * 发送时间(单位:毫秒)
     * </pre>
     *
     * <code>int64 sendTime = 2;</code>
     */
    private $sendTime = 0;
    /**
     * <pre>
     * 接收时间(单位:毫秒)
     * </pre>
     *
     * <code>int64 receiveTime = 3;</code>
     */
    private $receiveTime = 0;
    /**
     * <pre>
     *消息类型，详见 Type 枚举, Constant.Type
     * </pre>
     *
     * <code>int32 type = 4;</code>
     */
    private $type = 0;
    /**
     * <pre>
     *业务类型，详见 MsgType 枚举，Constant.MsgType
     * </pre>
     *
     * <code>int32 mType = 5;</code>
     */
    private $mType = 0;
    /**
     * <pre>
     *消息格式，详见 MsgFormat 枚举，Constant.MsgFormat
     * </pre>
     *
     * <code>int32 mFormat = 6;</code>
     */
    private $mFormat = 0;
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 sId = 7;</code>
     */
    private $sId = 0;
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>int64 rId = 8;</code>
     */
    private $rId = 0;
    /**
     * <pre>
     * 组ID
     * </pre>
     *
     * <code>int64 gId = 9;</code>
     */
    private $gId = 0;
    /**
     * <pre>
     * 消息版本号(用户／系统)，IM服务端生成。用于Client与IM进行消息同步。
     * </pre>
     *
     * <code>int64 msgVersion = 10;</code>
     */
    private $msgVersion = 0;
    /**
     * <pre>
     *子消息（群）版本号，IM服务端生成，用于同步子（群）消息。
     * </pre>
     *
     * <code>int64 subVersion = 11;</code>
     */
    private $subVersion = 0;
    /**
     * <pre>
     * 消息报文体。加密
     * </pre>
     *
     * <code>bytes body = 12;</code>
     */
    private $body = '';
    /**
     * <pre>
     * 消息状态：0：正常初始化 1：隐藏，默认为0
     * </pre>
     *
     * <code>int32 msgStatus = 13;</code>
     */
    private $msgStatus = 0;
    /**
     * <pre>
     *多语言标识，0:否 1:是 ，默认 0
     * </pre>
     *
     * <code>string multilang = 14;</code>
     */
    private $multilang = '';
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string ext = 15;</code>
     */
    private $ext = '';

    public function __construct() {
        \GPBMetadata\MsgActivity::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *消息ID,用于记录消息唯一标识(例如server端回ACK时,客户端可根据此ID唯一标识),对于业务报文此参数为必须
     * </pre>
     *
     * <code>string msgid = 1;</code>
     */
    public function getMsgid()
    {
        return $this->msgid;
    }

    /**
     * <pre>
     *消息ID,用于记录消息唯一标识(例如server端回ACK时,客户端可根据此ID唯一标识),对于业务报文此参数为必须
     * </pre>
     *
     * <code>string msgid = 1;</code>
     */
    public function setMsgid($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgid = $var;
    }

    /**
     * <pre>
     * 发送时间(单位:毫秒)
     * </pre>
     *
     * <code>int64 sendTime = 2;</code>
     */
    public function getSendTime()
    {
        return $this->sendTime;
    }

    /**
     * <pre>
     * 发送时间(单位:毫秒)
     * </pre>
     *
     * <code>int64 sendTime = 2;</code>
     */
    public function setSendTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->sendTime = $var;
    }

    /**
     * <pre>
     * 接收时间(单位:毫秒)
     * </pre>
     *
     * <code>int64 receiveTime = 3;</code>
     */
    public function getReceiveTime()
    {
        return $this->receiveTime;
    }

    /**
     * <pre>
     * 接收时间(单位:毫秒)
     * </pre>
     *
     * <code>int64 receiveTime = 3;</code>
     */
    public function setReceiveTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->receiveTime = $var;
    }

    /**
     * <pre>
     *消息类型，详见 Type 枚举, Constant.Type
     * </pre>
     *
     * <code>int32 type = 4;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <pre>
     *消息类型，详见 Type 枚举, Constant.Type
     * </pre>
     *
     * <code>int32 type = 4;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;
    }

    /**
     * <pre>
     *业务类型，详见 MsgType 枚举，Constant.MsgType
     * </pre>
     *
     * <code>int32 mType = 5;</code>
     */
    public function getMType()
    {
        return $this->mType;
    }

    /**
     * <pre>
     *业务类型，详见 MsgType 枚举，Constant.MsgType
     * </pre>
     *
     * <code>int32 mType = 5;</code>
     */
    public function setMType($var)
    {
        GPBUtil::checkInt32($var);
        $this->mType = $var;
    }

    /**
     * <pre>
     *消息格式，详见 MsgFormat 枚举，Constant.MsgFormat
     * </pre>
     *
     * <code>int32 mFormat = 6;</code>
     */
    public function getMFormat()
    {
        return $this->mFormat;
    }

    /**
     * <pre>
     *消息格式，详见 MsgFormat 枚举，Constant.MsgFormat
     * </pre>
     *
     * <code>int32 mFormat = 6;</code>
     */
    public function setMFormat($var)
    {
        GPBUtil::checkInt32($var);
        $this->mFormat = $var;
    }

    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 sId = 7;</code>
     */
    public function getSId()
    {
        return $this->sId;
    }

    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 sId = 7;</code>
     */
    public function setSId($var)
    {
        GPBUtil::checkInt64($var);
        $this->sId = $var;
    }

    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>int64 rId = 8;</code>
     */
    public function getRId()
    {
        return $this->rId;
    }

    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>int64 rId = 8;</code>
     */
    public function setRId($var)
    {
        GPBUtil::checkInt64($var);
        $this->rId = $var;
    }

    /**
     * <pre>
     * 组ID
     * </pre>
     *
     * <code>int64 gId = 9;</code>
     */
    public function getGId()
    {
        return $this->gId;
    }

    /**
     * <pre>
     * 组ID
     * </pre>
     *
     * <code>int64 gId = 9;</code>
     */
    public function setGId($var)
    {
        GPBUtil::checkInt64($var);
        $this->gId = $var;
    }

    /**
     * <pre>
     * 消息版本号(用户／系统)，IM服务端生成。用于Client与IM进行消息同步。
     * </pre>
     *
     * <code>int64 msgVersion = 10;</code>
     */
    public function getMsgVersion()
    {
        return $this->msgVersion;
    }

    /**
     * <pre>
     * 消息版本号(用户／系统)，IM服务端生成。用于Client与IM进行消息同步。
     * </pre>
     *
     * <code>int64 msgVersion = 10;</code>
     */
    public function setMsgVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->msgVersion = $var;
    }

    /**
     * <pre>
     *子消息（群）版本号，IM服务端生成，用于同步子（群）消息。
     * </pre>
     *
     * <code>int64 subVersion = 11;</code>
     */
    public function getSubVersion()
    {
        return $this->subVersion;
    }

    /**
     * <pre>
     *子消息（群）版本号，IM服务端生成，用于同步子（群）消息。
     * </pre>
     *
     * <code>int64 subVersion = 11;</code>
     */
    public function setSubVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->subVersion = $var;
    }

    /**
     * <pre>
     * 消息报文体。加密
     * </pre>
     *
     * <code>bytes body = 12;</code>
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * <pre>
     * 消息报文体。加密
     * </pre>
     *
     * <code>bytes body = 12;</code>
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;
    }

    /**
     * <pre>
     * 消息状态：0：正常初始化 1：隐藏，默认为0
     * </pre>
     *
     * <code>int32 msgStatus = 13;</code>
     */
    public function getMsgStatus()
    {
        return $this->msgStatus;
    }

    /**
     * <pre>
     * 消息状态：0：正常初始化 1：隐藏，默认为0
     * </pre>
     *
     * <code>int32 msgStatus = 13;</code>
     */
    public function setMsgStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->msgStatus = $var;
    }

    /**
     * <pre>
     *多语言标识，0:否 1:是 ，默认 0
     * </pre>
     *
     * <code>string multilang = 14;</code>
     */
    public function getMultilang()
    {
        return $this->multilang;
    }

    /**
     * <pre>
     *多语言标识，0:否 1:是 ，默认 0
     * </pre>
     *
     * <code>string multilang = 14;</code>
     */
    public function setMultilang($var)
    {
        GPBUtil::checkString($var, True);
        $this->multilang = $var;
    }

    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string ext = 15;</code>
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string ext = 15;</code>
     */
    public function setExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->ext = $var;
    }

}

