<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMServerActivity.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *用户登出报文
 *适用于：
 *消息类型 Type = OUT（登出）
 *Message 上行 需传字段：
 *version 消息报文版本
 *appkey  IM分配的appkey
 *sendTime    发送时间(单位:毫秒)
 *type    消息类型，详见 Type 枚举, Constant.Type
 *sId 发送者ID
 *body 消息报文体
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.Out</code>
 */
class Out extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 是否重连
     * </pre>
     *
     * <code>bool isReconn = 1;</code>
     */
    private $isReconn = false;
    /**
     * <pre>
     * 被强制退出时长(毫秒),若为0表示永久(MsgType=FORCED_OUT)
     * </pre>
     *
     * <code>int64 effectiveTime = 2;</code>
     */
    private $effectiveTime = 0;
    /**
     * <pre>
     *设备唯一标识，（处理同一个用户在不同设备上登录的情况）
     * </pre>
     *
     * <code>string deviceid = 3;</code>
     */
    private $deviceid = '';

    public function __construct() {
        \GPBMetadata\IMServerActivity::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 是否重连
     * </pre>
     *
     * <code>bool isReconn = 1;</code>
     */
    public function getIsReconn()
    {
        return $this->isReconn;
    }

    /**
     * <pre>
     * 是否重连
     * </pre>
     *
     * <code>bool isReconn = 1;</code>
     */
    public function setIsReconn($var)
    {
        GPBUtil::checkBool($var);
        $this->isReconn = $var;
    }

    /**
     * <pre>
     * 被强制退出时长(毫秒),若为0表示永久(MsgType=FORCED_OUT)
     * </pre>
     *
     * <code>int64 effectiveTime = 2;</code>
     */
    public function getEffectiveTime()
    {
        return $this->effectiveTime;
    }

    /**
     * <pre>
     * 被强制退出时长(毫秒),若为0表示永久(MsgType=FORCED_OUT)
     * </pre>
     *
     * <code>int64 effectiveTime = 2;</code>
     */
    public function setEffectiveTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->effectiveTime = $var;
    }

    /**
     * <pre>
     *设备唯一标识，（处理同一个用户在不同设备上登录的情况）
     * </pre>
     *
     * <code>string deviceid = 3;</code>
     */
    public function getDeviceid()
    {
        return $this->deviceid;
    }

    /**
     * <pre>
     *设备唯一标识，（处理同一个用户在不同设备上登录的情况）
     * </pre>
     *
     * <code>string deviceid = 3;</code>
     */
    public function setDeviceid($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceid = $var;
    }

}

