<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgActivity.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *拉取消息版本上行报文体，可选，如果不传将不会返回未读消息数量。
 *适用于：
 *1. 消息类型 type = PULL_ACT（拉取动作）
 *业务类型 mType = PULL_VERSION（拉取消息版本）
 *2. 消息类型 type = PING（心跳）
 *业务类型 mType = PULL_VERSION（拉取消息版本）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.PullVersions</code>
 */
class PullVersions extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *用户消息本地版本
     * </pre>
     *
     * <code>int64 userlv = 1;</code>
     */
    private $userlv = 0;
    /**
     * <pre>
     *系统广播消息本地版本
     * </pre>
     *
     * <code>int64 syslv = 2;</code>
     */
    private $syslv = 0;

    public function __construct() {
        \GPBMetadata\IMMsgActivity::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *用户消息本地版本
     * </pre>
     *
     * <code>int64 userlv = 1;</code>
     */
    public function getUserlv()
    {
        return $this->userlv;
    }

    /**
     * <pre>
     *用户消息本地版本
     * </pre>
     *
     * <code>int64 userlv = 1;</code>
     */
    public function setUserlv($var)
    {
        GPBUtil::checkInt64($var);
        $this->userlv = $var;
    }

    /**
     * <pre>
     *系统广播消息本地版本
     * </pre>
     *
     * <code>int64 syslv = 2;</code>
     */
    public function getSyslv()
    {
        return $this->syslv;
    }

    /**
     * <pre>
     *系统广播消息本地版本
     * </pre>
     *
     * <code>int64 syslv = 2;</code>
     */
    public function setSyslv($var)
    {
        GPBUtil::checkInt64($var);
        $this->syslv = $var;
    }

}

