<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMsgActivity.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 **
 *拉取离线版本下行报文体
 *适用于：
 *1. 消息类型 type = PULL_ACT（拉取动作）
 *业务类型 mType = PULL_VERSION（拉取消息版本）
 *2. 消息类型 type = SERVER_NOTICE（服务器通知）
 *业务类型 mType = PUSH_VERSION（消息版本）
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.PushVersions</code>
 */
class PushVersions extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *用户消息最新版本
     * </pre>
     *
     * <code>int64 usercv = 1;</code>
     */
    private $usercv = 0;
    /**
     * <pre>
     *用户用户消息 未读消息数量
     * </pre>
     *
     * <code>int64 usize = 2;</code>
     */
    private $usize = 0;
    /**
     * <pre>
     *系统广播消息最新版本
     * </pre>
     *
     * <code>int64 syscv = 3;</code>
     */
    private $syscv = 0;
    /**
     * <pre>
     *系统广播消息 未读消息数量
     * </pre>
     *
     * <code>int64 ssize = 4;</code>
     */
    private $ssize = 0;

    public function __construct() {
        \GPBMetadata\IMMsgActivity::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *用户消息最新版本
     * </pre>
     *
     * <code>int64 usercv = 1;</code>
     */
    public function getUsercv()
    {
        return $this->usercv;
    }

    /**
     * <pre>
     *用户消息最新版本
     * </pre>
     *
     * <code>int64 usercv = 1;</code>
     */
    public function setUsercv($var)
    {
        GPBUtil::checkInt64($var);
        $this->usercv = $var;
    }

    /**
     * <pre>
     *用户用户消息 未读消息数量
     * </pre>
     *
     * <code>int64 usize = 2;</code>
     */
    public function getUsize()
    {
        return $this->usize;
    }

    /**
     * <pre>
     *用户用户消息 未读消息数量
     * </pre>
     *
     * <code>int64 usize = 2;</code>
     */
    public function setUsize($var)
    {
        GPBUtil::checkInt64($var);
        $this->usize = $var;
    }

    /**
     * <pre>
     *系统广播消息最新版本
     * </pre>
     *
     * <code>int64 syscv = 3;</code>
     */
    public function getSyscv()
    {
        return $this->syscv;
    }

    /**
     * <pre>
     *系统广播消息最新版本
     * </pre>
     *
     * <code>int64 syscv = 3;</code>
     */
    public function setSyscv($var)
    {
        GPBUtil::checkInt64($var);
        $this->syscv = $var;
    }

    /**
     * <pre>
     *系统广播消息 未读消息数量
     * </pre>
     *
     * <code>int64 ssize = 4;</code>
     */
    public function getSsize()
    {
        return $this->ssize;
    }

    /**
     * <pre>
     *系统广播消息 未读消息数量
     * </pre>
     *
     * <code>int64 ssize = 4;</code>
     */
    public function setSsize($var)
    {
        GPBUtil::checkInt64($var);
        $this->ssize = $var;
    }

}

