<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMConstant.proto

namespace Protobuf\Garuda;

/**
 * <pre>
 *服务类型
 * </pre>
 *
 * Protobuf enum <code>protobuf.Garuda.ServerType</code>
 */
class ServerType
{
    /**
     * <pre>
     *tcp server
     * </pre>
     *
     * <code>CONNECTOR_TCP = 0;</code>
     */
    const CONNECTOR_TCP = 0;
    /**
     * <pre>
     *websocket server
     * </pre>
     *
     * <code>CONNECTOR_WS = 1;</code>
     */
    const CONNECTOR_WS = 1;
    /**
     * <pre>
     *a3s
     * </pre>
     *
     * <code>A3S = 2;</code>
     */
    const A3S = 2;
    /**
     * <pre>
     *普通 container
     * </pre>
     *
     * <code>CONTAINER_NORMAL = 3;</code>
     */
    const CONTAINER_NORMAL = 3;
    /**
     * <pre>
     *group
     * </pre>
     *
     * <code>CONTAINER_GROUP = 4;</code>
     */
    const CONTAINER_GROUP = 4;
}

