<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMConstant.proto

namespace Protobuf\Garuda;

/**
 * <pre>
 * 终端类型
 * </pre>
 *
 * Protobuf enum <code>protobuf.Garuda.TermType</code>
 */
class TermType
{
    /**
     * <pre>
     * 客户端使用
     * </pre>
     *
     * <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * <code>IPHONE = 1;</code>
     */
    const IPHONE = 1;
    /**
     * <code>ANDROID = 2;</code>
     */
    const ANDROID = 2;
    /**
     * <code>H5 = 3;</code>
     */
    const H5 = 3;
    /**
     * <pre>
     * PC网页
     * </pre>
     *
     * <code>WEB = 4;</code>
     */
    const WEB = 4;
    /**
     * <pre>
     * 手机网页
     * </pre>
     *
     * <code>WAP = 5;</code>
     */
    const WAP = 5;
    /**
     * <pre>
     * OBS
     * </pre>
     *
     * <code>OBS = 6;</code>
     */
    const OBS = 6;
}

