<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMConstant.proto

namespace Protobuf\Garuda;

/**
 * <pre>
 * 用户类型
 * </pre>
 *
 * Protobuf enum <code>protobuf.Garuda.UserType</code>
 */
class UserType
{
    /**
     * <pre>
     *默认，一般用户
     * </pre>
     *
     * <code>NORMAL = 0;</code>
     */
    const NORMAL = 0;
    /**
     * <pre>
     * 主播
     * </pre>
     *
     * <code>ANCHOR = 1;</code>
     */
    const ANCHOR = 1;
    /**
     * <pre>
     * 房间管理员
     * </pre>
     *
     * <code>MANAGER = 2;</code>
     */
    const MANAGER = 2;
    /**
     * <pre>
     * 机器人
     * </pre>
     *
     * <code>ROBOT = 3;</code>
     */
    const ROBOT = 3;
    /**
     * <pre>
     * 系统管理员
     * </pre>
     *
     * <code>ADMIN = 4;</code>
     */
    const ADMIN = 4;
    /**
     * <pre>
     *游客
     * </pre>
     *
     * <code>GUESS = 5;</code>
     */
    const GUESS = 5;
}

