<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMConstant.proto

namespace Protobuf\Garuda;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 用户信息
 * </pre>
 *
 * Protobuf type <code>protobuf.Garuda.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int64 uId = 1;</code>
     */
    private $uId = 0;
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string userName = 2;</code>
     */
    private $userName = '';
    /**
     * <pre>
     *用户图标
     * </pre>
     *
     * <code>string userIcon = 3;</code>
     */
    private $userIcon = '';
    /**
     * <pre>
     *用户等级
     * </pre>
     *
     * <code>int32 userGrade = 4;</code>
     */
    private $userGrade = 0;
    /**
     * <pre>
     *用户性别
     * </pre>
     *
     * <code>int32 userSex = 5;</code>
     */
    private $userSex = 0;
    /**
     * <pre>
     *vip
     * </pre>
     *
     * <code>int32 vip = 6;</code>
     */
    private $vip = 0;
    /**
     * <pre>
     *用户类型
     * </pre>
     *
     * <code>int32 uType = 7;</code>
     */
    private $uType = 0;
    /**
     * <pre>
     * 语言
     * </pre>
     *
     * <code>string lang = 8;</code>
     */
    private $lang = '';
    /**
     * <pre>
     * 国家码
     * </pre>
     *
     * <code>string cc = 9;</code>
     */
    private $cc = '';

    public function __construct() {
        \GPBMetadata\IMConstant::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int64 uId = 1;</code>
     */
    public function getUId()
    {
        return $this->uId;
    }

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int64 uId = 1;</code>
     */
    public function setUId($var)
    {
        GPBUtil::checkInt64($var);
        $this->uId = $var;
    }

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string userName = 2;</code>
     */
    public function getUserName()
    {
        return $this->userName;
    }

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string userName = 2;</code>
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->userName = $var;
    }

    /**
     * <pre>
     *用户图标
     * </pre>
     *
     * <code>string userIcon = 3;</code>
     */
    public function getUserIcon()
    {
        return $this->userIcon;
    }

    /**
     * <pre>
     *用户图标
     * </pre>
     *
     * <code>string userIcon = 3;</code>
     */
    public function setUserIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->userIcon = $var;
    }

    /**
     * <pre>
     *用户等级
     * </pre>
     *
     * <code>int32 userGrade = 4;</code>
     */
    public function getUserGrade()
    {
        return $this->userGrade;
    }

    /**
     * <pre>
     *用户等级
     * </pre>
     *
     * <code>int32 userGrade = 4;</code>
     */
    public function setUserGrade($var)
    {
        GPBUtil::checkInt32($var);
        $this->userGrade = $var;
    }

    /**
     * <pre>
     *用户性别
     * </pre>
     *
     * <code>int32 userSex = 5;</code>
     */
    public function getUserSex()
    {
        return $this->userSex;
    }

    /**
     * <pre>
     *用户性别
     * </pre>
     *
     * <code>int32 userSex = 5;</code>
     */
    public function setUserSex($var)
    {
        GPBUtil::checkInt32($var);
        $this->userSex = $var;
    }

    /**
     * <pre>
     *vip
     * </pre>
     *
     * <code>int32 vip = 6;</code>
     */
    public function getVip()
    {
        return $this->vip;
    }

    /**
     * <pre>
     *vip
     * </pre>
     *
     * <code>int32 vip = 6;</code>
     */
    public function setVip($var)
    {
        GPBUtil::checkInt32($var);
        $this->vip = $var;
    }

    /**
     * <pre>
     *用户类型
     * </pre>
     *
     * <code>int32 uType = 7;</code>
     */
    public function getUType()
    {
        return $this->uType;
    }

    /**
     * <pre>
     *用户类型
     * </pre>
     *
     * <code>int32 uType = 7;</code>
     */
    public function setUType($var)
    {
        GPBUtil::checkInt32($var);
        $this->uType = $var;
    }

    /**
     * <pre>
     * 语言
     * </pre>
     *
     * <code>string lang = 8;</code>
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * <pre>
     * 语言
     * </pre>
     *
     * <code>string lang = 8;</code>
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;
    }

    /**
     * <pre>
     * 国家码
     * </pre>
     *
     * <code>string cc = 9;</code>
     */
    public function getCc()
    {
        return $this->cc;
    }

    /**
     * <pre>
     * 国家码
     * </pre>
     *
     * <code>string cc = 9;</code>
     */
    public function setCc($var)
    {
        GPBUtil::checkString($var, True);
        $this->cc = $var;
    }

}

